---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bhadrika/public_html/tubesitw22.bhadrikais.my.id/company
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
